import {
  mkdirSync,
  copyFileSync,
  readdirSync,
  existsSync,
  writeFileSync,
  cpSync,
  readFileSync,
} from "node:fs";
import { execSync } from "node:child_process";
import { join, dirname, resolve } from "node:path";
import { workspacePaths, findTemplatesDir } from "./paths.js";
import { listBundledSkills, type Skill } from "./skills-registry.js";

export type ScaffoldResult = {
  root: string;
  installedSkills: string[];
  gitInitialized: boolean;
};

function isDirEmptyEnough(dir: string): boolean {
  if (!existsSync(dir)) return true;
  const entries = readdirSync(dir).filter((e) => e !== ".DS_Store");
  return entries.length === 0;
}

export function scaffoldWorkspace(targetDir: string): ScaffoldResult {
  const root = resolve(targetDir);
  if (existsSync(root) && !isDirEmptyEnough(root)) {
    throw new Error(
      `target "${root}" already exists and is not empty. ` +
        "refusing to overwrite. pick an empty dir or remove it first.",
    );
  }

  const p = workspacePaths(root);
  mkdirSync(p.root, { recursive: true });
  mkdirSync(p.sources, { recursive: true });
  mkdirSync(p.graph, { recursive: true });
  mkdirSync(p.knowledge, { recursive: true });
  mkdirSync(p.claudeSkills, { recursive: true });

  // Templates
  const tpl = findTemplatesDir();
  copyFileSync(join(tpl, "CLAUDE.md"), p.claudeMd);
  copyFileSync(join(tpl, "gitignore.tmpl"), p.gitignore);

  // Stub READMEs in each empty folder so git tracks them.
  writeFileSync(
    join(p.sources, "README.md"),
    "# sources\n\nDrop research files here, then run `mogkit add` to tag them.\n",
  );
  writeFileSync(
    join(p.graph, "README.md"),
    "# graph\n\n`graph.json` and `graph.md` are generated by the `graphify` skill.\n",
  );
  writeFileSync(
    join(p.knowledge, "README.md"),
    "# knowledge\n\nOutputs from interrogation skills land here.\n",
  );

  // Install all bundled skills.
  const installed = installAllSkills(p.claudeSkills);

  // git init (best-effort; not fatal if git missing).
  let gitInitialized = false;
  try {
    execSync("git init -q", { cwd: p.root, stdio: "pipe" });
    gitInitialized = true;
  } catch {
    gitInitialized = false;
  }

  return { root: p.root, installedSkills: installed, gitInitialized };
}

function installAllSkills(claudeSkillsDir: string): string[] {
  const installed: string[] = [];
  for (const s of listBundledSkills()) {
    installSkillToWorkspace(claudeSkillsDir, s);
    installed.push(s.name);
  }
  return installed.sort();
}

export function installSkillToWorkspace(
  claudeSkillsDir: string,
  skill: Skill,
): void {
  const dst = join(claudeSkillsDir, skill.name);
  mkdirSync(dirname(dst), { recursive: true });
  cpSync(skill.dir, dst, { recursive: true });
}

/**
 * Walk up from `start` looking for a mogkit workspace root.
 * Returns the directory or null if none found before filesystem root.
 */
export function findWorkspaceRoot(start: string = process.cwd()): string | null {
  let dir = resolve(start);
  // Limit traversal depth to avoid surprises.
  for (let i = 0; i < 20; i++) {
    const p = workspacePaths(dir);
    if (existsSync(p.claudeMd) && existsSync(p.sources)) return dir;
    const parent = dirname(dir);
    if (parent === dir) return null;
    dir = parent;
  }
  return null;
}

/** Used by tests / utilities; reads CLAUDE.md to confirm it's a mogkit one. */
export function isMogkitClaudeMd(claudeMdPath: string): boolean {
  if (!existsSync(claudeMdPath)) return false;
  const head = readFileSync(claudeMdPath, "utf8").slice(0, 200);
  return head.includes("mogkit workspace");
}
